config/routes.rb
Rails.application.eager_load! if Rails.env.development?

class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Peatio::Application.routes.draw do
  use_doorkeeper

  root 'welcome#index'

  if Rails.env.development?
    mount MailsViewer::Engine => '/mails'
  end

  get '/signin' => 'sessions#new', :as => :signin
  get '/signup' => 'identities#new', :as => :signup
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure', :as => :failure
  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]

  resource :member, :only => [:edit, :update]
  resource :identity, :only => [:edit, :update]

  namespace :verify do
    resource :sms_auth,    only: [:show, :update]
    resource :google_auth, only: [:show, :update, :edit, :destroy]
  end

  namespace :authentications do
    resources :emails, only: [:new, :create]
    resources :identities, only: [:new, :create]
    resource :weibo_accounts, only: [:destroy]
  end

  scope :constraints => { id: /[a-zA-Z0-9]{32}/ } do
    resources :reset_passwords
    resources :activations, only: [:new, :edit, :update]
  end

  get '/documents/api_v2'
  get '/documents/websocket_api'
  get '/documents/oauth'
  resources :documents, only: [:show]
  resources :two_factors, only: [:show, :index, :update]

  scope module: :private do
    resource  :id_document, only: [:edit, :update]

    resources :settings, only: [:index]
    resources :api_tokens do
      member do
        delete :unbind
      end
    end

    resources :fund_sources, only: [:create, :update, :destroy]

    resources :funds, only: [:index] do
      collection do
        post :gen_address
      end
    end

    namespace :deposits do
      Deposit.descendants.each do |d|
        resources d.resource_name do
          collection do
            post :gen_address
          end
        end
      end
    end

    namespace :withdraws do
      Withdraw.descendants.each do |w|
        resources w.resource_name
      end
    end

    resources :account_versions, :only => :index

    resources :exchange_assets, :controller => 'assets' do
      member do
        get :partial_tree
      end
    end

    get '/history/orders' => 'history#orders', as: :order_history
    get '/history/trades' => 'history#trades', as: :trade_history
    get '/history/account' => 'history#account', as: :account_history

    resources :markets, :only => :show, :constraints => MarketConstraint do
      resources :orders, :only => [:index, :destroy] do
        collection do
          post :clear
        end
      end
      resources :order_bids, :only => [:create] do
        collection do
          post :clear
        end
      end
      resources :order_asks, :only => [:create] do
        collection do
          post :clear
        end
      end
    end

    post '/pusher/auth', to: 'pusher#auth'

    resources :tickets, only: [:index, :new, :create, :show] do
      member do
        patch :close
      end
      resources :comments, only: [:create]
    end
  end

  draw :admin

  mount APIv2::Mount => APIv2::Mount::PREFIX

end

app/controllers/private/account_versions_controller.rb
module Private
  class AccountVersionsController < BaseController
    def index
      @account_versions_grid = AccountVersionsGrid.new(params[:account_versions_grid]) do |scope|
        scope.where(:member_id => current_user.id)
      end
      @assets = @account_versions_grid.assets.page(params[:page]).per(20)
    end
  end
end

app/controllers/private/api_tokens_controller.rb
module Private
  class APITokensController < BaseController
    before_action :auth_activated!
    before_action :auth_verified!
    before_action :two_factor_activated!

    def index
      @tokens = current_user.api_tokens.user_requested
      @oauth_api_tokens = current_user.api_tokens.oauth_requested

      ids = Doorkeeper::AccessToken
        .where(id: @oauth_api_tokens.map(&:oauth_access_token_id))
        .group(:application_id).select('max(id) as id')
      @oauth_access_tokens = Doorkeeper::AccessToken.where(id: ids).includes(:application)
    end

    def new
      @token = current_user.api_tokens.build
    end

    def create
      @token = current_user.api_tokens.build api_token_params
      @token.scopes = 'all'

      if !two_factor_auth_verified?
        flash.now[:alert] = t('.alert_two_factor')
        render :new and return
      end

      if @token.save
        flash.now[:notice] = t('.success')
      else
        flash.now[:alert] = t('.failed')
        render :new
      end
    end

    def edit
      @token = current_user.api_tokens.user_requested.find params[:id]
    end

    def update
      @token = current_user.api_tokens.user_requested.find params[:id]

      if !two_factor_auth_verified?
        flash.now[:alert] = t('.alert_two_factor')
        render :edit and return
      end

      if @token.update_attributes(api_token_params)
        flash.now[:notice] = t('.success')
      else
        flash.now[:alert] = t('.failed')
      end

      render :edit
    end

    def destroy
      @token = current_user.api_tokens.user_requested.find params[:id]
      if @token.destroy
        redirect_to url_for(action: :index), notice: t('.success')
      else
        redirect_to url_for(action: :index), notice: t('.failed')
      end
    end

    def unbind
      Doorkeeper::AccessToken.revoke_all_for(params[:id], current_user)
      redirect_to url_for(action: :index), notice: t('.success')
    end

    private

    def api_token_params
      params.require(:api_token).permit(:label, :ip_whitelist)
    end

  end
end

app/controllers/private/assets_controller.rb
module Private
  class AssetsController < BaseController
    skip_before_action :auth_member!, only: [:index]

    def index
      @cny_assets  = Currency.assets('cny')
      @btc_proof   = Proof.current :btc
      @cny_proof   = Proof.current :cny

      if current_user
        @btc_account = current_user.accounts.with_currency(:btc).first
        @cny_account = current_user.accounts.with_currency(:cny).first
      end
    end

    def partial_tree
      account    = current_user.accounts.with_currency(params[:id]).first
      @timestamp = Proof.with_currency(params[:id]).last.timestamp
      @json      = account.partial_tree.to_json.html_safe
      respond_to do |format|
        format.js
      end
    end

  end
end

app/controllers/private/base_controller.rb
module Private
  class BaseController < ::ApplicationController
    before_action :check_email_nil
    before_filter :no_cache, :auth_member!

    private

    def no_cache
      response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
      response.headers["Pragma"] = "no-cache"
      response.headers["Expires"] = "Sat, 03 Jan 2009 00:00:00 GMT"
    end

    def check_email_nil
      redirect_to new_authentications_email_path if current_user && current_user.email.nil?
    end

  end
end

app/controllers/private/comments_controller.rb
module Private
  class CommentsController < BaseController

    def create
      comment = ticket.comments.new(comment_params.merge(author_id: current_user.id))

      if comment.save
        flash[:notice] = I18n.t("private.tickets.comment_succ")
      else
        flash[:alert] = I18n.t("private.tickets.comment_fail")
      end
      redirect_to ticket_path(ticket)
    end

    private

    def comment_params
      params.required(:comment).permit(:content)
    end

    def ticket
      @ticket ||= current_user.tickets.find(params[:ticket_id])
    end

  end
end

app/controllers/private/deposits/banks_controller.rb
module Private
  module Deposits
    class BanksController < ::Private::Deposits::BaseController
      include ::Deposits::CtrlBankable
    end
  end
end

app/controllers/private/deposits/base_controller.rb
module Private
  module Deposits
    class BaseController < ::Private::BaseController
      layout 'app'
      before_action :channel
      before_action :auth_activated!
      before_action :auth_verified!

      def channel
        @channel ||= DepositChannel.find_by_key(self.controller_name.singularize)
      end

      def model_kls
        "deposits/#{self.controller_name.singularize}".camelize.constantize
      end
    end
  end
end

app/controllers/private/deposits/nzbanks_controller.rb
module Private
  module Deposits
    class NzbanksController < ::Private::Deposits::BaseController
      include ::Deposits::CtrlBankable
    end
  end
end

app/controllers/private/deposits/satoshis_controller.rb
module Private
  module Deposits
    class SatoshisController < ::Private::Deposits::BaseController
      include ::Deposits::CtrlCoinable
    end
  end
end

app/controllers/private/fund_sources_controller.rb
module Private
  class FundSourcesController < BaseController

    def create
      new_fund_source = current_user.fund_sources.new fund_source_params

      if new_fund_source.save
        render json: new_fund_source, status: :ok
      else
        head :bad_request
      end
    end

    def update
      account = current_user.accounts.with_currency(fund_source.currency).first
      account.update default_withdraw_fund_source_id: params[:id]

      head :ok
    end

    def destroy
      render json: fund_source.destroy, status: :ok
    end

    private

    def fund_source
      current_user.fund_sources.find(params[:id])
    end

    def fund_source_params
      params.require(:fund_source).permit(:currency, :uid, :extra)
    end
  end
end

app/controllers/private/funds_controller.rb
module Private
  class FundsController < BaseController
    layout 'funds'

    before_action :auth_activated!
    before_action :auth_verified!
    before_action :two_factor_activated!

    def index
      @deposit_channels = DepositChannel.all
      @withdraw_channels = WithdrawChannel.all
      @currencies = Currency.all.sort
      @deposits = current_user.deposits
      @accounts = current_user.accounts.enabled
      @withdraws = current_user.withdraws
      @fund_sources = current_user.fund_sources
      @banks = Bank.all

      gon.jbuilder
    end

    def gen_address
      current_user.accounts.each do |account|
        next if not account.currency_obj.coin?

        if account.payment_addresses.blank?
          account.payment_addresses.create(currency: account.currency)
        else
          address = account.payment_addresses.last
          address.gen_address if address.address.blank?
        end
      end
      render nothing: true
    end

  end
end

app/controllers/private/history_controller.rb
module Private
  class HistoryController < BaseController

    helper_method :tabs

    def account
      @market = current_market

      @deposits = Deposit.where(member: current_user).with_aasm_state(:accepted)
      @withdraws = Withdraw.where(member: current_user).with_aasm_state(:done)

      @transactions = (@deposits + @withdraws).sort_by {|t| -t.created_at.to_i }
      @transactions = Kaminari.paginate_array(@transactions).page(params[:page]).per(20)
    end

    def trades
      @trades = current_user.trades
        .includes(:ask_member).includes(:bid_member)
        .order('id desc').page(params[:page]).per(20)
    end

    def orders
      @orders = current_user.orders.includes(:trades).order("id desc").page(params[:page]).per(20)
    end

    private

    def tabs
      { order: ['header.order_history', order_history_path],
        trade: ['header.trade_history', trade_history_path],
        account: ['header.account_history', account_history_path] }
    end

  end
end

app/controllers/private/id_documents_controller.rb
module Private
  class IdDocumentsController < BaseController

    def edit
      @id_document = current_user.id_document || current_user.create_id_document
    end

    def update
      @id_document = current_user.id_document

      if @id_document.update_attributes id_document_params
        @id_document.submit! if @id_document.unverified?

        redirect_to settings_path, notice: t('.notice')
      else
        render :edit
      end
    end

    private

    def id_document_params
      params.require(:id_document).permit(:name, :birth_date, :address, :city, :country, :zipcode,
                                          :id_document_type, :id_document_number, :id_bill_type,
                                          {id_document_file_attributes: [:id, :file]},
                                          {id_bill_file_attributes: [:id, :file]})
    end
  end
end

app/controllers/private/markets_controller.rb
module Private
  class MarketsController < BaseController
    skip_before_action :auth_member!, only: [:show]
    before_action :visible_market?
    after_action :set_default_market

    layout false

    def show
      @bid = params[:bid]
      @ask = params[:ask]

      @market        = current_market
      @markets       = Market.all.sort
      @market_groups = @markets.map(&:quote_unit).uniq

      @bids   = @market.bids
      @asks   = @market.asks
      @trades = @market.trades

      # default to limit order
      @order_bid = OrderBid.new ord_type: 'limit'
      @order_ask = OrderAsk.new ord_type: 'limit'

      set_member_data if current_user
      gon.jbuilder
    end

    private

    def visible_market?
      redirect_to market_path(Market.first) if not current_market.visible?
    end

    def set_default_market
      cookies[:market_id] = @market.id
    end

    def set_member_data
      @member = current_user
      @orders_wait = @member.orders.with_currency(@market).with_state(:wait)
      @trades_done = Trade.for_member(@market.id, current_user, limit: 100, order: 'id desc')
    end

  end
end

app/controllers/private/order_asks_controller.rb
module Private
  class OrderAsksController < BaseController
    include Concerns::OrderCreation

    def create
      @order = OrderAsk.new(order_params(:order_ask))
      order_submit
    end

    def clear
      @orders = OrderAsk.where(member_id: current_user.id).with_state(:wait).with_currency(current_market)
      Ordering.new(@orders).cancel
      render status: 200, nothing: true
    end

  end
end

app/controllers/private/order_bids_controller.rb
module Private
  class OrderBidsController < BaseController
    include Concerns::OrderCreation

    def create
      @order = OrderBid.new(order_params(:order_bid))
      order_submit
    end

    def clear
      @orders = OrderBid.where(member_id: current_user.id).with_state(:wait).with_currency(current_market)
      Ordering.new(@orders).cancel
      render status: 200, nothing: true
    end

  end
end

app/controllers/private/orders_controller.rb
module Private
  class OrdersController < BaseController

    def destroy
      ActiveRecord::Base.transaction do
        order = current_user.orders.find(params[:id])
        ordering = Ordering.new(order)

        if ordering.cancel
          render status: 200, nothing: true
        else
          render status: 500, nothing: true
        end
      end
    end

    def clear
      @orders = current_user.orders.with_currency(current_market).with_state(:wait)
      Ordering.new(@orders).cancel
      render status: 200, nothing: true
    end

  end
end

app/controllers/private/payment_addresses_controller.rb
module Private
  class PaymentAddressesController < BaseController
    def update
      account = current_user.get_account(params[:currency])
      payment_address = account.payment_addresses.using
      unless payment_address.transactions.empty?
        account.gen_payment_address
      end
      redirect_to funds_path
    end
  end
end

app/controllers/private/pusher_controller.rb
require "openssl"

module Private
  class PusherController < BaseController
    protect_from_forgery :except => :auth
  
    def auth
      sn = params[:channel_name].split('-', 2).last
      if current_user && current_user.sn == sn
        response = Pusher[params[:channel_name]].authenticate(params[:socket_id])
        render :json => response
      else
        render :text => "Forbidden", :status => '403'
      end
    end
  end
end

app/controllers/private/settings_controller.rb
module Private
  class SettingsController < BaseController
    def index
      unless current_user.activated?
        flash.now[:info] = t('.activated')
      end
    end
  end
end

app/views/private/settings/index.html.slim
table#setting_list.table
  tr
    td.col-xs-2.text-center.vertical-center: i.fa.fa-envelope-o.fa-2x
    td.col-xs-15
      h4 = t('.email.title')
      - if current_user.activated?
        p.text-ignore = t('.email.description-activated')
      - else
        p.text-ignore = t('.email.description')
    td.col-xs-7.vertical-center
      - if current_user.activated?
        a href="#" class="btn btn-success btn-block disabled" role="button"
          i.fa.fa-check-circle
          span = t('.email.activated')
      - else
        = link_to t('.email.resend'), new_activation_path, class: 'btn btn-default btn-block'
  tr
    td.col-xs-2.text-center.vertical-center: i.fa.fa-thumbs-o-up.fa-2x
    td.col-xs-15
      h4
        span = t('.verification.title')
        i.fa.fa-bolt.text-warning
      p.text-ignore = t('.verification.description')
    td.col-xs-7.vertical-center
      - if current_user.id_document_verified?
        a href="#" class="btn btn-success btn-block disabled" role="button"
          i.fa.fa-check-circle
          span = t('.verification.verified')
      - else
        = link_to t('.verification.go'), edit_id_document_path, class: 'btn btn-default btn-block'
  tr
    td.col-xs-2.text-center.vertical-center: i.fa.fa-mobile.fa-4x
    td.col-xs-15
      h4
        span = t('.phone_number.title')
        i.fa.fa-bolt.text-warning
      p.text-ignore = t('.phone_number.description')
    td.col-xs-7.vertical-center
      - if current_user.sms_two_factor.activated?
        a href="#" class="btn btn-success btn-block disabled" role="button"
          i.fa.fa-check-circle
          span = t('.phone_number.verified')
        .hint = t('.phone_number.hint', hint: partial_phone_number(current_user))
      - else
        = link_to t('.phone_number.go'), verify_sms_auth_path, class: 'btn btn-default btn-block'
  tr
    td.col-xs-2.text-center.vertical-center: i.fa.fa-superscript.fa-2x
    td.col-xs-15
      h4
        span = t('.two_factor_auth.title')
        i.fa.fa-bolt.text-warning
      p.text-ignore = t('.two_factor_auth.description')
    td.col-xs-7.vertical-center
      - if current_user.app_two_factor.activated?
        = link_to t('.two_factor_auth.disable'), edit_verify_google_auth_path, class: 'btn btn-default btn-block'
      - else
        = link_to t('.two_factor_auth.enable'), verify_google_auth_path, class: 'btn btn-default btn-block'
  tr
    td.col-xs-2.text-center.vertical-center: i.fa.fa-key.fa-2x
    td.col-xs-15
      h4 = t('.passwords.title')
      p.text-ignore = t('.passwords.description')
    td.col-xs-7.vertical-center
      - if current_user.identity
        = link_to t('.passwords.go'), edit_identity_path, class: 'btn btn-default btn-block'
      - else
        = link_to t('.passwords.set'), new_authentications_identity_path, class: 'btn btn-default btn-block'
  tr
    td.col-xs-2.text-center.vertical-center: i.fa.fa-code.fa-2x
    td.col-xs-15
      h4 = t('.api_tokens.title')
      p.text-ignore = t('.api_tokens.description')
    td.col-xs-7.vertical-center
      = link_to t('.api_tokens.go'), api_tokens_path, class: 'btn btn-default btn-block'
  - if ENV["WEIBO_AUTH"] == "true"
    tr
      td.col-xs-2.text-center.vertical-center: i.fa.fa-weibo.fa-2x
      td.col-xs-15
        h4 = t(".weibo.title")
        - if current_user.auth_with?('weibo')
          p.text-ignore = t(".weibo.bound_desc", { nickname: current_user.auth('weibo').nickname })
        - else
          p.text-ignore = t(".weibo.description")
      td.col-xs-7.vertical-center
        - if current_user.auth_with?('weibo')
          = link_to t('.weibo.unbind'), authentications_weibo_accounts_path, method: :delete, class: 'btn btn-success btn-block'
        - else
          = link_to t('.weibo.bind'), '/auth/weibo', class: 'btn btn-default btn-block'

= content_for :guide_title do
  h3
    i.fa.fa-user
    span = current_user.email

= content_for :guide do
  ul.list-group
    - if current_user.admin?
      span.label.label-warning ADMIN
    - current_user.tag_list.each do |key|
      span.label.label-info
        = member_tag(key)
  p.text-warning
    == t('.safety_instruction')